spring.application.name=auth-service

server.port=8081



spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.hikari.initializationFailTimeout=60000

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
# Mostra os comandos SQL no console
spring.jpa.show-sql=true

# Formata os comandos SQL para melhor visualização
spring.jpa.properties.hibernate.format_sql=true

#Insert
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update

jwt.secret=sua_chave_secreta_muito_segura_com_mais_de_256_bits_para_hs256