services:
  db:
    image: mysql:8.0
    container_name: auth-db
    restart: always
    environment:
      MYSQL_DATABASE: bancoauth
      MYSQL_ROOT_PASSWORD: fatec
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./insert.sql:/docker-entrypoint-initdb.d/import.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 10

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bancoauth?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=fatec
      - JWT_SECRET=sua_chave_secreta_muito_segura_com_mais_de_256_bits_para_hs256
    depends_on:
       db:
         condition: service_healthy

volumes:
  db_data: